// This file is generated by a tool, from the `languageCodez.tsv` file in this repository
Lang{ 0x7273, 44, "srpski" },
Lang{ 0x7362, 56, "bosanski" },
Lang{ 0x7268, 32, "hrvatski" },
Lang{ 0x7173, 58, "albanski" },
Lang{ 0x6B6D, 49, "makedonski" },
Lang{ 0x6C73, 46, "slovenski" },
Lang{ 0x6E65, 0, "engleski" },
